name: Azure Login
description: Logs into Azure using a service principal
inputs:
  client-id:
    description: The Client ID of the Azure Managed Identity
    required: true
  tenant-id:
    description: The Tenant ID of the Azure Managed Identity (i.e. the Azure Active Directory in which the Identity lives)
    required: true

runs:
  using: "composite"
  steps:
    - name: Obtain OpenID Connect token
      uses: actions/github-script@v7
        id: token
        with:
          script: |
            const token = await core.getIDToken('api://AzureADTokenExchange')
            core.setSecret(token)
            return token

    - name: Azure Login
      shell: bash
      run: |
        echo "Logging into Azure..."
        az login --service-principal \
          --username ${{ inputs.client-id }} \
          --tenant ${{ inputs.tenant-id }} \
          --federated-token ${{ steps.token.outputs.result }} \
          --output none
