name: Break Pacman Upload Lease

on:
  workflow_dispatch:

jobs:
  break-lease:
    if: github.event.repository.owner.login == 'git-for-windows'
    runs-on: ubuntu-latest
    steps:
      - name: Clone build-extra
        uses: actions/checkout@v4
        with:
          repository: git-for-windows/build-extra

      - name: Prepare home directory
        if: env.AZURE_BLOBS_TOKEN != ''
        env:
          AZURE_BLOBS_TOKEN: ${{secrets.AZURE_BLOBS_TOKEN}}
        shell: bash
        run: |
          echo "::add-mask::$(echo "$AZURE_BLOBS_TOKEN" | base64 -w 0)" &&
          echo "$AZURE_BLOBS_TOKEN" >"$HOME"/.azure-blobs-token

      - name: Break the lease
        if: env.AZURE_BLOBS_TOKEN != ''
        shell: bash
        env:
          AZURE_BLOBS_TOKEN: ${{secrets.AZURE_BLOBS_TOKEN}}
        run: |
          ./pacman-helper.sh break_lock
