name: Break Pacman Upload Lease

on:
  workflow_dispatch:

jobs:
  break-lease:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Clone build-extra
        uses: actions/checkout@v5
        with:
          repository: git-for-windows/build-extra
      - name: Break the lease
        if: env.azure_blobs_token != ''
        shell: bash
        env:
          azure_blobs_token: ${{secrets.AZURE_BLOBS_TOKEN}}
        run: |
          echo "::add-mask::$(echo "$AZURE_BLOBS_TOKEN" | base64 -w 0)" &&
          ./pacman-helper.sh break_lock
