name: delete azure-self-hosted-runner
run-name: Delete ${{ inputs.runner_name }}

on:
  workflow_dispatch:
    inputs:
      runner_name:
        type: string
        required: true
        description: The name of the runner that needs to be deleted

env:
  ACTIONS_RUNNER_NAME: ${{ github.event.inputs.runner_name }}

permissions:
  id-token: write # required for Azure login via OIDC

# The following secrets are required for this workflow to run:
# AZURE_CLIENT_ID - The Client ID of an Azure Managed Identity. It is recommended to set up a resource
#                   group specifically for self-hosted Actions Runners, and to add a federated identity
#                   to authenticate as the currently-running GitHub workflow.
#   az identity create --name <managed-identity-name> -g <resource-group>
#   az identity federated-credential create \
#     --identity-name <managed-identity-name> \
#     --resource-group <resource-group> \
#     --name github-workflow \
#     --issuer https://token.actions.githubusercontent.com \
#     --subject repo:git-for-windows/git-for-windows-automation:ref:refs/heads/main \
#     --audiences api://AzureADTokenExchange
#   MSYS_NO_PATHCONV=1 \
#   az role assignment create \
#     --assignee <client-id-of-managed-identity> \
#     --scope '/subscriptions/<subscription-id>/resourceGroups/<resource-group>' \
#     --role 'Contributor'
# AZURE_TENANT_ID - The Tenant ID of the Azure Managed Identity (i.e. the Azure Active Directory in which
#                   the Identity lives)
# AZURE_SUBSCRIPTION_ID - The Subscription ID with which the Azure Managed Identity is associated
#                         (technically, this is not necessary for `az login --service-principal` with a
#                         managed identity, but `Azure/login` requires it anyway)
# AZURE_RESOURCE_GROUP - Resource group to find the runner in. It's recommended to set up a resource
#                        group specifically for self-hosted Actions Runners.
jobs:
  delete-runner:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Delete VM '${{ env.ACTIONS_RUNNER_NAME }}'
      uses: azure/CLI@v2
      with:
        azcliversion: 2.64.0
        inlineScript: |
          az vm delete -n "$ACTIONS_RUNNER_NAME" -g ${{ secrets.AZURE_RESOURCE_GROUP }} --yes
          az network nsg delete -n "$ACTIONS_RUNNER_NAME"-nsg -g ${{ secrets.AZURE_RESOURCE_GROUP }}
          az network vnet delete -n "$ACTIONS_RUNNER_NAME"-vnet -g ${{ secrets.AZURE_RESOURCE_GROUP }}
          az network public-ip delete -n "$ACTIONS_RUNNER_NAME"-ip -g ${{ secrets.AZURE_RESOURCE_GROUP }}
